#!/usr/bin/env node

var exec = require('child_process').exec;
var servedRegex = /^assets.+$|^.+\.html$/gm;
exec('./node_modules/grunt-cli/bin/grunt dist', function(error, stdout, stderr){
  if(error){
    console.log(stderr);
    process.exit(0);
  }
  else {
    console.log(stdout);
    exec("git ls-files -m", function(error, stdout, stderr){
      var servedFiles = stdout.match(servedRegex);
      
      if(servedFiles){
        console.log('The following served files that haven\'t been added to the index:\n')
        console.log(servedFiles.join('\n'));
        console.log('\nPlease add these files prior to your commit.');
        process.exit(1);
      }
    });
  }
});

